services:
  nodejs:
    build: .
    command: npm run start
    container_name: nest
    volumes:
      - ".:/var/www/app"
    ports:
      - "8070:3000"
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:15.3-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB_HOST: "localhost"
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: db
  #   ports:
  #     - "5432:5432"