services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nodejs:
    depends_on:
        - postgres
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: nestjs
    volumes:
      - ".:/var/www"
    ports:
      - "8080:3000"
    command: >
      sh -c "npm install; npm run start"
  
volumes:
  pgdata:
      